server:
  port: 8000
  servlet:
    session:
      timeout: 30m

spring:
  thymeleaf:
    cache: false
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true
  mvc:
    servlet:
      load-on-startup: 100
  resources:
    static-locations: classpath:templates/
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://:3306/gulimall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      username: root
      password: 
  redis:
    host: 
    password: 
  cloud:
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: 
        bucket: 
#  main:
#    allow-bean-definition-overriding: true

secretId: 
secretKey: 

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间,
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间,默认为1s
        ReadTimeOut: 5000

logging:
  level:
    com.jnu.gulimall: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10